//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/5/2022 11:46:41 PM
namespace OpenData.Entities
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for KindergartenApp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<KindergartenApp> KindergartenApp
        {
            get
            {
                if ((this._KindergartenApp == null))
                {
                    this._KindergartenApp = base.CreateQuery<KindergartenApp>("KindergartenApp");
                }
                return this._KindergartenApp;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<KindergartenApp> _KindergartenApp;
        /// <summary>
        /// There are no comments for BodyOfWaters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BodyOfWater> BodyOfWaters
        {
            get
            {
                if ((this._BodyOfWaters == null))
                {
                    this._BodyOfWaters = base.CreateQuery<BodyOfWater>("BodyOfWaters");
                }
                return this._BodyOfWaters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BodyOfWater> _BodyOfWaters;
        /// <summary>
        /// There are no comments for DeclaredPersons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DeclaredPersons> DeclaredPersons
        {
            get
            {
                if ((this._DeclaredPersons == null))
                {
                    this._DeclaredPersons = base.CreateQuery<DeclaredPersons>("DeclaredPersons");
                }
                return this._DeclaredPersons;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DeclaredPersons> _DeclaredPersons;
        /// <summary>
        /// There are no comments for GovernmentBankAccounts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GovernmentBankAccounts> GovernmentBankAccounts
        {
            get
            {
                if ((this._GovernmentBankAccounts == null))
                {
                    this._GovernmentBankAccounts = base.CreateQuery<GovernmentBankAccounts>("GovernmentBankAccounts");
                }
                return this._GovernmentBankAccounts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GovernmentBankAccounts> _GovernmentBankAccounts;
        /// <summary>
        /// There are no comments for MarriageRegisters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MarriageRegister> MarriageRegisters
        {
            get
            {
                if ((this._MarriageRegisters == null))
                {
                    this._MarriageRegisters = base.CreateQuery<MarriageRegister>("MarriageRegisters");
                }
                return this._MarriageRegisters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MarriageRegister> _MarriageRegisters;
        /// <summary>
        /// There are no comments for BirthRegisters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BirthRegister> BirthRegisters
        {
            get
            {
                if ((this._BirthRegisters == null))
                {
                    this._BirthRegisters = base.CreateQuery<BirthRegister>("BirthRegisters");
                }
                return this._BirthRegisters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BirthRegister> _BirthRegisters;
        /// <summary>
        /// There are no comments for Districts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<District> Districts
        {
            get
            {
                if ((this._Districts == null))
                {
                    this._Districts = base.CreateQuery<District>("Districts");
                }
                return this._Districts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<District> _Districts;
        /// <summary>
        /// There are no comments for KindergartenApp in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToKindergartenApp(KindergartenApp kindergartenApp)
        {
            base.AddObject("KindergartenApp", kindergartenApp);
        }
        /// <summary>
        /// There are no comments for BodyOfWaters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBodyOfWaters(BodyOfWater bodyOfWater)
        {
            base.AddObject("BodyOfWaters", bodyOfWater);
        }
        /// <summary>
        /// There are no comments for DeclaredPersons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDeclaredPersons(DeclaredPersons declaredPersons)
        {
            base.AddObject("DeclaredPersons", declaredPersons);
        }
        /// <summary>
        /// There are no comments for GovernmentBankAccounts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGovernmentBankAccounts(GovernmentBankAccounts governmentBankAccounts)
        {
            base.AddObject("GovernmentBankAccounts", governmentBankAccounts);
        }
        /// <summary>
        /// There are no comments for MarriageRegisters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMarriageRegisters(MarriageRegister marriageRegister)
        {
            base.AddObject("MarriageRegisters", marriageRegister);
        }
        /// <summary>
        /// There are no comments for BirthRegisters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBirthRegisters(BirthRegister birthRegister)
        {
            base.AddObject("BirthRegisters", birthRegister);
        }
        /// <summary>
        /// There are no comments for Districts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDistricts(District district)
        {
            base.AddObject("Districts", district);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"OpenData.Entities\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/ed" +
                "m\"><EntityType Name=\"KindergartenApp\"><Key><PropertyRef Name=\"id\" /></Key><Prope" +
                "rty Name=\"id\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"district_id\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"child_uid\" Type=\"Edm.String\" " +
                "/><Property Name=\"registered_date\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Prope" +
                "rty Name=\"desirable_start_school_year\" Type=\"Edm.String\" /><Property Name=\"group" +
                "_language\" Type=\"Edm.String\" /><Property Name=\"group_language_en\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"status_name\" Type=\"Edm.String\" /><Property Name=\"status_na" +
                "me_en\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"BodyOfWater\"><Key><Pro" +
                "pertyRef Name=\"id\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\"" +
                " /><Property Name=\"title\" Type=\"Edm.String\" /><Property Name=\"kl_bwtr_id\" Type=\"" +
                "Edm.String\" /><Property Name=\"kl_regn_id\" Type=\"Edm.String\" /><Property Name=\"pr" +
                "vd_id\" Type=\"Edm.Int32\" /><Property Name=\"description\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"asdescription_en\" Type=\"Edm.String\" /><Property Name=\"search_key\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"active\" Type=\"Edm.Int32\" /><Property Name=\"lati" +
                "tude\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property Name=\"longitude\" Type=\"Edm" +
                ".Decimal\" Nullable=\"false\" /><Property Name=\"polygon\" Type=\"Edm.String\" /></Enti" +
                "tyType><EntityType Name=\"DeclaredPersons\"><Key><PropertyRef Name=\"id\" /></Key><P" +
                "roperty Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"year\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"month\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" /><Property Name=\"day\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Na" +
                "me=\"value\" Type=\"Edm.Decimal\" Nullable=\"false\" /><Property Name=\"district_id\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"district_name\" Type=\"Edm.Strin" +
                "g\" /></EntityType><EntityType Name=\"GovernmentBankAccounts\"><Key><PropertyRef Na" +
                "me=\"id\" /></Key><Property Name=\"id\" Type=\"Edm.String\" Nullable=\"false\" /><Proper" +
                "ty Name=\"district_id\" Type=\"Edm.Int32\" /><Property Name=\"district_name\" Type=\"Ed" +
                "m.String\" /><Property Name=\"district_region_id\" Type=\"Edm.Int32\" /><Property Nam" +
                "e=\"district_region_name\" Type=\"Edm.String\" /><Property Name=\"account_number\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"account_name\" Type=\"Edm.String\" /><Property Nam" +
                "e=\"account_currency\" Type=\"Edm.String\" /><Property Name=\"bank_swift\" Type=\"Edm.S" +
                "tring\" /><Property Name=\"bank_name\" Type=\"Edm.String\" /><Property Name=\"reg_numb" +
                "er\" Type=\"Edm.String\" /><Property Name=\"account_purpose\" Type=\"Edm.String\" /></E" +
                "ntityType><EntityType Name=\"MarriageRegister\"><Key><PropertyRef Name=\"id\" /></Ke" +
                "y><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"reg_pl" +
                "ace\" Type=\"Edm.String\" /><Property Name=\"merr_year\" Type=\"Edm.Int32\" /><Property" +
                " Name=\"merr_month\" Type=\"Edm.Int32\" /><Property Name=\"merr_place\" Type=\"Edm.Stri" +
                "ng\" /><Property Name=\"husb_age\" Type=\"Edm.Int32\" /><Property Name=\"husb_merr_cou" +
                "nt\" Type=\"Edm.Int32\" /><Property Name=\"wife_age\" Type=\"Edm.Int32\" /><Property Na" +
                "me=\"wife_merr_count\" Type=\"Edm.Int32\" /><Property Name=\"district_id\" Type=\"Edm.I" +
                "nt32\" /></EntityType><EntityType Name=\"BirthRegister\"><Key><PropertyRef Name=\"id" +
                "\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"reg_place\" Type=\"Edm.String\" /><Property Name=\"first_name\" Type=\"Edm.String\" /" +
                "><Property Name=\"other_names\" Type=\"Edm.String\" /><Property Name=\"birth_date\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"sex\" Type=\"Edm.Int32\" /><Property Name=\"distri" +
                "ct_id\" Type=\"Edm.Int32\" /><Property Name=\"active_date\" Type=\"Edm.DateTime\" Nulla" +
                "ble=\"false\" /></EntityType><EntityType Name=\"District\"><Key><PropertyRef Name=\"i" +
                "d\" /></Key><Property Name=\"id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Nam" +
                "e=\"district_atvk\" Type=\"Edm.String\" /><Property Name=\"district_name\" Type=\"Edm.S" +
                "tring\" /></EntityType></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas" +
                ".microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEnt" +
                "ityContainer=\"true\"><EntitySet Name=\"KindergartenApp\" EntityType=\"OpenData.Entit" +
                "ies.KindergartenApp\" /><EntitySet Name=\"BodyOfWaters\" EntityType=\"OpenData.Entit" +
                "ies.BodyOfWater\" /><EntitySet Name=\"DeclaredPersons\" EntityType=\"OpenData.Entiti" +
                "es.DeclaredPersons\" /><EntitySet Name=\"GovernmentBankAccounts\" EntityType=\"OpenD" +
                "ata.Entities.GovernmentBankAccounts\" /><EntitySet Name=\"MarriageRegisters\" Entit" +
                "yType=\"OpenData.Entities.MarriageRegister\" /><EntitySet Name=\"BirthRegisters\" En" +
                "tityType=\"OpenData.Entities.BirthRegister\" /><EntitySet Name=\"Districts\" EntityT" +
                "ype=\"OpenData.Entities.District\" /></EntityContainer></Schema></edmx:DataService" +
                "s></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.KindergartenApp in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("KindergartenApp")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class KindergartenApp : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new KindergartenApp object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="district_id">Initial value of district_id.</param>
        /// <param name="registered_date">Initial value of registered_date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static KindergartenApp CreateKindergartenApp(long ID, int district_id, global::System.DateTime registered_date)
        {
            KindergartenApp kindergartenApp = new KindergartenApp();
            kindergartenApp.id = ID;
            kindergartenApp.district_id = district_id;
            kindergartenApp.registered_date = registered_date;
            return kindergartenApp;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property district_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int district_id
        {
            get
            {
                return this._district_id;
            }
            set
            {
                this.Ondistrict_idChanging(value);
                this._district_id = value;
                this.Ondistrict_idChanged();
                this.OnPropertyChanged("district_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _district_id;
        partial void Ondistrict_idChanging(int value);
        partial void Ondistrict_idChanged();
        /// <summary>
        /// There are no comments for Property child_uid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string child_uid
        {
            get
            {
                return this._child_uid;
            }
            set
            {
                this.Onchild_uidChanging(value);
                this._child_uid = value;
                this.Onchild_uidChanged();
                this.OnPropertyChanged("child_uid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _child_uid;
        partial void Onchild_uidChanging(string value);
        partial void Onchild_uidChanged();
        /// <summary>
        /// There are no comments for Property registered_date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime registered_date
        {
            get
            {
                return this._registered_date;
            }
            set
            {
                this.Onregistered_dateChanging(value);
                this._registered_date = value;
                this.Onregistered_dateChanged();
                this.OnPropertyChanged("registered_date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _registered_date;
        partial void Onregistered_dateChanging(global::System.DateTime value);
        partial void Onregistered_dateChanged();
        /// <summary>
        /// There are no comments for Property desirable_start_school_year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string desirable_start_school_year
        {
            get
            {
                return this._desirable_start_school_year;
            }
            set
            {
                this.Ondesirable_start_school_yearChanging(value);
                this._desirable_start_school_year = value;
                this.Ondesirable_start_school_yearChanged();
                this.OnPropertyChanged("desirable_start_school_year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _desirable_start_school_year;
        partial void Ondesirable_start_school_yearChanging(string value);
        partial void Ondesirable_start_school_yearChanged();
        /// <summary>
        /// There are no comments for Property group_language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string group_language
        {
            get
            {
                return this._group_language;
            }
            set
            {
                this.Ongroup_languageChanging(value);
                this._group_language = value;
                this.Ongroup_languageChanged();
                this.OnPropertyChanged("group_language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _group_language;
        partial void Ongroup_languageChanging(string value);
        partial void Ongroup_languageChanged();
        /// <summary>
        /// There are no comments for Property group_language_en in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string group_language_en
        {
            get
            {
                return this._group_language_en;
            }
            set
            {
                this.Ongroup_language_enChanging(value);
                this._group_language_en = value;
                this.Ongroup_language_enChanged();
                this.OnPropertyChanged("group_language_en");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _group_language_en;
        partial void Ongroup_language_enChanging(string value);
        partial void Ongroup_language_enChanged();
        /// <summary>
        /// There are no comments for Property status_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status_name
        {
            get
            {
                return this._status_name;
            }
            set
            {
                this.Onstatus_nameChanging(value);
                this._status_name = value;
                this.Onstatus_nameChanged();
                this.OnPropertyChanged("status_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status_name;
        partial void Onstatus_nameChanging(string value);
        partial void Onstatus_nameChanged();
        /// <summary>
        /// There are no comments for Property status_name_en in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string status_name_en
        {
            get
            {
                return this._status_name_en;
            }
            set
            {
                this.Onstatus_name_enChanging(value);
                this._status_name_en = value;
                this.Onstatus_name_enChanged();
                this.OnPropertyChanged("status_name_en");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _status_name_en;
        partial void Onstatus_name_enChanging(string value);
        partial void Onstatus_name_enChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.BodyOfWater in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BodyOfWaters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class BodyOfWater : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BodyOfWater object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="latitude">Initial value of latitude.</param>
        /// <param name="longitude">Initial value of longitude.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BodyOfWater CreateBodyOfWater(int ID, decimal latitude, decimal longitude)
        {
            BodyOfWater bodyOfWater = new BodyOfWater();
            bodyOfWater.id = ID;
            bodyOfWater.latitude = latitude;
            bodyOfWater.longitude = longitude;
            return bodyOfWater;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this.OntitleChanging(value);
                this._title = value;
                this.OntitleChanged();
                this.OnPropertyChanged("title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _title;
        partial void OntitleChanging(string value);
        partial void OntitleChanged();
        /// <summary>
        /// There are no comments for Property kl_bwtr_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string kl_bwtr_id
        {
            get
            {
                return this._kl_bwtr_id;
            }
            set
            {
                this.Onkl_bwtr_idChanging(value);
                this._kl_bwtr_id = value;
                this.Onkl_bwtr_idChanged();
                this.OnPropertyChanged("kl_bwtr_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _kl_bwtr_id;
        partial void Onkl_bwtr_idChanging(string value);
        partial void Onkl_bwtr_idChanged();
        /// <summary>
        /// There are no comments for Property kl_regn_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string kl_regn_id
        {
            get
            {
                return this._kl_regn_id;
            }
            set
            {
                this.Onkl_regn_idChanging(value);
                this._kl_regn_id = value;
                this.Onkl_regn_idChanged();
                this.OnPropertyChanged("kl_regn_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _kl_regn_id;
        partial void Onkl_regn_idChanging(string value);
        partial void Onkl_regn_idChanged();
        /// <summary>
        /// There are no comments for Property prvd_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> prvd_id
        {
            get
            {
                return this._prvd_id;
            }
            set
            {
                this.Onprvd_idChanging(value);
                this._prvd_id = value;
                this.Onprvd_idChanged();
                this.OnPropertyChanged("prvd_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _prvd_id;
        partial void Onprvd_idChanging(global::System.Nullable<int> value);
        partial void Onprvd_idChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property asdescription_en in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string asdescription_en
        {
            get
            {
                return this._asdescription_en;
            }
            set
            {
                this.Onasdescription_enChanging(value);
                this._asdescription_en = value;
                this.Onasdescription_enChanged();
                this.OnPropertyChanged("asdescription_en");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _asdescription_en;
        partial void Onasdescription_enChanging(string value);
        partial void Onasdescription_enChanged();
        /// <summary>
        /// There are no comments for Property search_key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string search_key
        {
            get
            {
                return this._search_key;
            }
            set
            {
                this.Onsearch_keyChanging(value);
                this._search_key = value;
                this.Onsearch_keyChanged();
                this.OnPropertyChanged("search_key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _search_key;
        partial void Onsearch_keyChanging(string value);
        partial void Onsearch_keyChanged();
        /// <summary>
        /// There are no comments for Property active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> active
        {
            get
            {
                return this._active;
            }
            set
            {
                this.OnactiveChanging(value);
                this._active = value;
                this.OnactiveChanged();
                this.OnPropertyChanged("active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _active;
        partial void OnactiveChanging(global::System.Nullable<int> value);
        partial void OnactiveChanged();
        /// <summary>
        /// There are no comments for Property latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal latitude
        {
            get
            {
                return this._latitude;
            }
            set
            {
                this.OnlatitudeChanging(value);
                this._latitude = value;
                this.OnlatitudeChanged();
                this.OnPropertyChanged("latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _latitude;
        partial void OnlatitudeChanging(decimal value);
        partial void OnlatitudeChanged();
        /// <summary>
        /// There are no comments for Property longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal longitude
        {
            get
            {
                return this._longitude;
            }
            set
            {
                this.OnlongitudeChanging(value);
                this._longitude = value;
                this.OnlongitudeChanged();
                this.OnPropertyChanged("longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _longitude;
        partial void OnlongitudeChanging(decimal value);
        partial void OnlongitudeChanged();
        /// <summary>
        /// There are no comments for Property polygon in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string polygon
        {
            get
            {
                return this._polygon;
            }
            set
            {
                this.OnpolygonChanging(value);
                this._polygon = value;
                this.OnpolygonChanged();
                this.OnPropertyChanged("polygon");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _polygon;
        partial void OnpolygonChanging(string value);
        partial void OnpolygonChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.DeclaredPersons in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DeclaredPersons")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class DeclaredPersons : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DeclaredPersons object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="year">Initial value of year.</param>
        /// <param name="month">Initial value of month.</param>
        /// <param name="day">Initial value of day.</param>
        /// <param name="value">Initial value of value.</param>
        /// <param name="district_id">Initial value of district_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DeclaredPersons CreateDeclaredPersons(int ID, int year, int month, int day, decimal value, int district_id)
        {
            DeclaredPersons declaredPersons = new DeclaredPersons();
            declaredPersons.id = ID;
            declaredPersons.year = year;
            declaredPersons.month = month;
            declaredPersons.day = day;
            declaredPersons.value = value;
            declaredPersons.district_id = district_id;
            return declaredPersons;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int year
        {
            get
            {
                return this._year;
            }
            set
            {
                this.OnyearChanging(value);
                this._year = value;
                this.OnyearChanged();
                this.OnPropertyChanged("year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _year;
        partial void OnyearChanging(int value);
        partial void OnyearChanged();
        /// <summary>
        /// There are no comments for Property month in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int month
        {
            get
            {
                return this._month;
            }
            set
            {
                this.OnmonthChanging(value);
                this._month = value;
                this.OnmonthChanged();
                this.OnPropertyChanged("month");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _month;
        partial void OnmonthChanging(int value);
        partial void OnmonthChanged();
        /// <summary>
        /// There are no comments for Property day in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int day
        {
            get
            {
                return this._day;
            }
            set
            {
                this.OndayChanging(value);
                this._day = value;
                this.OndayChanged();
                this.OnPropertyChanged("day");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _day;
        partial void OndayChanging(int value);
        partial void OndayChanged();
        /// <summary>
        /// There are no comments for Property value in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal value
        {
            get
            {
                return this._value;
            }
            set
            {
                this.OnvalueChanging(value);
                this._value = value;
                this.OnvalueChanged();
                this.OnPropertyChanged("value");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _value;
        partial void OnvalueChanging(decimal value);
        partial void OnvalueChanged();
        /// <summary>
        /// There are no comments for Property district_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int district_id
        {
            get
            {
                return this._district_id;
            }
            set
            {
                this.Ondistrict_idChanging(value);
                this._district_id = value;
                this.Ondistrict_idChanged();
                this.OnPropertyChanged("district_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _district_id;
        partial void Ondistrict_idChanging(int value);
        partial void Ondistrict_idChanged();
        /// <summary>
        /// There are no comments for Property district_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string district_name
        {
            get
            {
                return this._district_name;
            }
            set
            {
                this.Ondistrict_nameChanging(value);
                this._district_name = value;
                this.Ondistrict_nameChanged();
                this.OnPropertyChanged("district_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _district_name;
        partial void Ondistrict_nameChanging(string value);
        partial void Ondistrict_nameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.GovernmentBankAccounts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GovernmentBankAccounts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class GovernmentBankAccounts : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GovernmentBankAccounts object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GovernmentBankAccounts CreateGovernmentBankAccounts(string ID)
        {
            GovernmentBankAccounts governmentBankAccounts = new GovernmentBankAccounts();
            governmentBankAccounts.id = ID;
            return governmentBankAccounts;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _id;
        partial void OnidChanging(string value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property district_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> district_id
        {
            get
            {
                return this._district_id;
            }
            set
            {
                this.Ondistrict_idChanging(value);
                this._district_id = value;
                this.Ondistrict_idChanged();
                this.OnPropertyChanged("district_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _district_id;
        partial void Ondistrict_idChanging(global::System.Nullable<int> value);
        partial void Ondistrict_idChanged();
        /// <summary>
        /// There are no comments for Property district_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string district_name
        {
            get
            {
                return this._district_name;
            }
            set
            {
                this.Ondistrict_nameChanging(value);
                this._district_name = value;
                this.Ondistrict_nameChanged();
                this.OnPropertyChanged("district_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _district_name;
        partial void Ondistrict_nameChanging(string value);
        partial void Ondistrict_nameChanged();
        /// <summary>
        /// There are no comments for Property district_region_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> district_region_id
        {
            get
            {
                return this._district_region_id;
            }
            set
            {
                this.Ondistrict_region_idChanging(value);
                this._district_region_id = value;
                this.Ondistrict_region_idChanged();
                this.OnPropertyChanged("district_region_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _district_region_id;
        partial void Ondistrict_region_idChanging(global::System.Nullable<int> value);
        partial void Ondistrict_region_idChanged();
        /// <summary>
        /// There are no comments for Property district_region_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string district_region_name
        {
            get
            {
                return this._district_region_name;
            }
            set
            {
                this.Ondistrict_region_nameChanging(value);
                this._district_region_name = value;
                this.Ondistrict_region_nameChanged();
                this.OnPropertyChanged("district_region_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _district_region_name;
        partial void Ondistrict_region_nameChanging(string value);
        partial void Ondistrict_region_nameChanged();
        /// <summary>
        /// There are no comments for Property account_number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string account_number
        {
            get
            {
                return this._account_number;
            }
            set
            {
                this.Onaccount_numberChanging(value);
                this._account_number = value;
                this.Onaccount_numberChanged();
                this.OnPropertyChanged("account_number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _account_number;
        partial void Onaccount_numberChanging(string value);
        partial void Onaccount_numberChanged();
        /// <summary>
        /// There are no comments for Property account_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string account_name
        {
            get
            {
                return this._account_name;
            }
            set
            {
                this.Onaccount_nameChanging(value);
                this._account_name = value;
                this.Onaccount_nameChanged();
                this.OnPropertyChanged("account_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _account_name;
        partial void Onaccount_nameChanging(string value);
        partial void Onaccount_nameChanged();
        /// <summary>
        /// There are no comments for Property account_currency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string account_currency
        {
            get
            {
                return this._account_currency;
            }
            set
            {
                this.Onaccount_currencyChanging(value);
                this._account_currency = value;
                this.Onaccount_currencyChanged();
                this.OnPropertyChanged("account_currency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _account_currency;
        partial void Onaccount_currencyChanging(string value);
        partial void Onaccount_currencyChanged();
        /// <summary>
        /// There are no comments for Property bank_swift in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string bank_swift
        {
            get
            {
                return this._bank_swift;
            }
            set
            {
                this.Onbank_swiftChanging(value);
                this._bank_swift = value;
                this.Onbank_swiftChanged();
                this.OnPropertyChanged("bank_swift");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _bank_swift;
        partial void Onbank_swiftChanging(string value);
        partial void Onbank_swiftChanged();
        /// <summary>
        /// There are no comments for Property bank_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string bank_name
        {
            get
            {
                return this._bank_name;
            }
            set
            {
                this.Onbank_nameChanging(value);
                this._bank_name = value;
                this.Onbank_nameChanged();
                this.OnPropertyChanged("bank_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _bank_name;
        partial void Onbank_nameChanging(string value);
        partial void Onbank_nameChanged();
        /// <summary>
        /// There are no comments for Property reg_number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string reg_number
        {
            get
            {
                return this._reg_number;
            }
            set
            {
                this.Onreg_numberChanging(value);
                this._reg_number = value;
                this.Onreg_numberChanged();
                this.OnPropertyChanged("reg_number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _reg_number;
        partial void Onreg_numberChanging(string value);
        partial void Onreg_numberChanged();
        /// <summary>
        /// There are no comments for Property account_purpose in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string account_purpose
        {
            get
            {
                return this._account_purpose;
            }
            set
            {
                this.Onaccount_purposeChanging(value);
                this._account_purpose = value;
                this.Onaccount_purposeChanged();
                this.OnPropertyChanged("account_purpose");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _account_purpose;
        partial void Onaccount_purposeChanging(string value);
        partial void Onaccount_purposeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.MarriageRegister in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MarriageRegisters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class MarriageRegister : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MarriageRegister object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MarriageRegister CreateMarriageRegister(int ID)
        {
            MarriageRegister marriageRegister = new MarriageRegister();
            marriageRegister.id = ID;
            return marriageRegister;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property reg_place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string reg_place
        {
            get
            {
                return this._reg_place;
            }
            set
            {
                this.Onreg_placeChanging(value);
                this._reg_place = value;
                this.Onreg_placeChanged();
                this.OnPropertyChanged("reg_place");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _reg_place;
        partial void Onreg_placeChanging(string value);
        partial void Onreg_placeChanged();
        /// <summary>
        /// There are no comments for Property merr_year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> merr_year
        {
            get
            {
                return this._merr_year;
            }
            set
            {
                this.Onmerr_yearChanging(value);
                this._merr_year = value;
                this.Onmerr_yearChanged();
                this.OnPropertyChanged("merr_year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _merr_year;
        partial void Onmerr_yearChanging(global::System.Nullable<int> value);
        partial void Onmerr_yearChanged();
        /// <summary>
        /// There are no comments for Property merr_month in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> merr_month
        {
            get
            {
                return this._merr_month;
            }
            set
            {
                this.Onmerr_monthChanging(value);
                this._merr_month = value;
                this.Onmerr_monthChanged();
                this.OnPropertyChanged("merr_month");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _merr_month;
        partial void Onmerr_monthChanging(global::System.Nullable<int> value);
        partial void Onmerr_monthChanged();
        /// <summary>
        /// There are no comments for Property merr_place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string merr_place
        {
            get
            {
                return this._merr_place;
            }
            set
            {
                this.Onmerr_placeChanging(value);
                this._merr_place = value;
                this.Onmerr_placeChanged();
                this.OnPropertyChanged("merr_place");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _merr_place;
        partial void Onmerr_placeChanging(string value);
        partial void Onmerr_placeChanged();
        /// <summary>
        /// There are no comments for Property husb_age in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> husb_age
        {
            get
            {
                return this._husb_age;
            }
            set
            {
                this.Onhusb_ageChanging(value);
                this._husb_age = value;
                this.Onhusb_ageChanged();
                this.OnPropertyChanged("husb_age");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _husb_age;
        partial void Onhusb_ageChanging(global::System.Nullable<int> value);
        partial void Onhusb_ageChanged();
        /// <summary>
        /// There are no comments for Property husb_merr_count in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> husb_merr_count
        {
            get
            {
                return this._husb_merr_count;
            }
            set
            {
                this.Onhusb_merr_countChanging(value);
                this._husb_merr_count = value;
                this.Onhusb_merr_countChanged();
                this.OnPropertyChanged("husb_merr_count");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _husb_merr_count;
        partial void Onhusb_merr_countChanging(global::System.Nullable<int> value);
        partial void Onhusb_merr_countChanged();
        /// <summary>
        /// There are no comments for Property wife_age in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> wife_age
        {
            get
            {
                return this._wife_age;
            }
            set
            {
                this.Onwife_ageChanging(value);
                this._wife_age = value;
                this.Onwife_ageChanged();
                this.OnPropertyChanged("wife_age");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _wife_age;
        partial void Onwife_ageChanging(global::System.Nullable<int> value);
        partial void Onwife_ageChanged();
        /// <summary>
        /// There are no comments for Property wife_merr_count in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> wife_merr_count
        {
            get
            {
                return this._wife_merr_count;
            }
            set
            {
                this.Onwife_merr_countChanging(value);
                this._wife_merr_count = value;
                this.Onwife_merr_countChanged();
                this.OnPropertyChanged("wife_merr_count");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _wife_merr_count;
        partial void Onwife_merr_countChanging(global::System.Nullable<int> value);
        partial void Onwife_merr_countChanged();
        /// <summary>
        /// There are no comments for Property district_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> district_id
        {
            get
            {
                return this._district_id;
            }
            set
            {
                this.Ondistrict_idChanging(value);
                this._district_id = value;
                this.Ondistrict_idChanged();
                this.OnPropertyChanged("district_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _district_id;
        partial void Ondistrict_idChanging(global::System.Nullable<int> value);
        partial void Ondistrict_idChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.BirthRegister in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BirthRegisters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class BirthRegister : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BirthRegister object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        /// <param name="active_date">Initial value of active_date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BirthRegister CreateBirthRegister(int ID, global::System.DateTime active_date)
        {
            BirthRegister birthRegister = new BirthRegister();
            birthRegister.id = ID;
            birthRegister.active_date = active_date;
            return birthRegister;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property reg_place in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string reg_place
        {
            get
            {
                return this._reg_place;
            }
            set
            {
                this.Onreg_placeChanging(value);
                this._reg_place = value;
                this.Onreg_placeChanged();
                this.OnPropertyChanged("reg_place");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _reg_place;
        partial void Onreg_placeChanging(string value);
        partial void Onreg_placeChanged();
        /// <summary>
        /// There are no comments for Property first_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string first_name
        {
            get
            {
                return this._first_name;
            }
            set
            {
                this.Onfirst_nameChanging(value);
                this._first_name = value;
                this.Onfirst_nameChanged();
                this.OnPropertyChanged("first_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _first_name;
        partial void Onfirst_nameChanging(string value);
        partial void Onfirst_nameChanged();
        /// <summary>
        /// There are no comments for Property other_names in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string other_names
        {
            get
            {
                return this._other_names;
            }
            set
            {
                this.Onother_namesChanging(value);
                this._other_names = value;
                this.Onother_namesChanged();
                this.OnPropertyChanged("other_names");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _other_names;
        partial void Onother_namesChanging(string value);
        partial void Onother_namesChanged();
        /// <summary>
        /// There are no comments for Property birth_date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string birth_date
        {
            get
            {
                return this._birth_date;
            }
            set
            {
                this.Onbirth_dateChanging(value);
                this._birth_date = value;
                this.Onbirth_dateChanged();
                this.OnPropertyChanged("birth_date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _birth_date;
        partial void Onbirth_dateChanging(string value);
        partial void Onbirth_dateChanged();
        /// <summary>
        /// There are no comments for Property sex in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> sex
        {
            get
            {
                return this._sex;
            }
            set
            {
                this.OnsexChanging(value);
                this._sex = value;
                this.OnsexChanged();
                this.OnPropertyChanged("sex");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _sex;
        partial void OnsexChanging(global::System.Nullable<int> value);
        partial void OnsexChanged();
        /// <summary>
        /// There are no comments for Property district_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> district_id
        {
            get
            {
                return this._district_id;
            }
            set
            {
                this.Ondistrict_idChanging(value);
                this._district_id = value;
                this.Ondistrict_idChanged();
                this.OnPropertyChanged("district_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _district_id;
        partial void Ondistrict_idChanging(global::System.Nullable<int> value);
        partial void Ondistrict_idChanged();
        /// <summary>
        /// There are no comments for Property active_date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime active_date
        {
            get
            {
                return this._active_date;
            }
            set
            {
                this.Onactive_dateChanging(value);
                this._active_date = value;
                this.Onactive_dateChanged();
                this.OnPropertyChanged("active_date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _active_date;
        partial void Onactive_dateChanging(global::System.DateTime value);
        partial void Onactive_dateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenData.Entities.District in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Districts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class District : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new District object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static District CreateDistrict(int ID)
        {
            District district = new District();
            district.id = ID;
            return district;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property district_atvk in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string district_atvk
        {
            get
            {
                return this._district_atvk;
            }
            set
            {
                this.Ondistrict_atvkChanging(value);
                this._district_atvk = value;
                this.Ondistrict_atvkChanged();
                this.OnPropertyChanged("district_atvk");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _district_atvk;
        partial void Ondistrict_atvkChanging(string value);
        partial void Ondistrict_atvkChanged();
        /// <summary>
        /// There are no comments for Property district_name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string district_name
        {
            get
            {
                return this._district_name;
            }
            set
            {
                this.Ondistrict_nameChanging(value);
                this._district_name = value;
                this.Ondistrict_nameChanged();
                this.OnPropertyChanged("district_name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _district_name;
        partial void Ondistrict_nameChanging(string value);
        partial void Ondistrict_nameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
